
spring:
  application:
    name: ead-notification-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
      # credencias para acessar config-server com a implementação de spring-security
      username: configserver
      password: 'ead123cs'



